"""empty message

Revision ID: 9aa173aec503
Revises: 
Create Date: 2018-04-07 08:45:35.045648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa173aec503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=False),
    sa.Column('kelamin', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ayam')
    # ### end Alembic commands ###
